"""Generates a synthetic Flipkart-style order dataset for return-risk modeling.

Produces data/orders.csv with order/customer/product attributes and a binary
`returned` label. The label is driven by a hand-tuned logistic model over the
generated features so that the resulting dataset has realistic, learnable
structure (customer history and payment method matter most) plus injected
MAR missingness in `rating_given` tied to `payment_method`.
"""
import os

import numpy as np
import pandas as pd

SEED = 42
N_ORDERS = 6000

CATEGORY_PROBS = {
    "Apparel": 0.30,
    "Electronics": 0.20,
    "Home": 0.18,
    "Footwear": 0.17,
    "Beauty": 0.15,
}

PRICE_RANGES = {
    "Apparel": (350, 2500),
    "Electronics": (1000, 50000),
    "Home": (500, 15000),
    "Footwear": (500, 6000),
    "Beauty": (150, 3000),
}

PAYMENT_PROBS = {
    "COD": 0.40,
    "Prepaid_Card": 0.25,
    "Prepaid_UPI": 0.25,
    "Wallet": 0.10,
}

RETURN_PRONE_CATEGORIES = {"Apparel", "Footwear"}


def generate(n_orders: int = N_ORDERS, seed: int = SEED) -> pd.DataFrame:
    rng = np.random.default_rng(seed)

    categories = rng.choice(
        list(CATEGORY_PROBS.keys()), size=n_orders, p=list(CATEGORY_PROBS.values())
    )
    payment_methods = rng.choice(
        list(PAYMENT_PROBS.keys()), size=n_orders, p=list(PAYMENT_PROBS.values())
    )

    price_inr = np.array(
        [rng.uniform(*PRICE_RANGES[cat]) for cat in categories]
    ).round(2)

    discount_pct = np.clip(rng.normal(loc=20, scale=14, size=n_orders), 0, 70).round(1)

    customer_tenure_days = np.clip(
        rng.exponential(scale=420, size=n_orders), 1, 2600
    ).astype(int)

    num_previous_orders = np.clip(
        (customer_tenure_days / 45.0) + rng.normal(0, 3, size=n_orders), 0, None
    ).astype(int)

    return_propensity = rng.beta(a=1.4, b=8.0, size=n_orders)
    num_previous_returns = np.minimum(
        num_previous_orders, rng.binomial(num_previous_orders, return_propensity)
    )

    delivery_distance_km = np.clip(
        rng.gamma(shape=3.0, scale=85, size=n_orders), 2, 2200
    ).round(1)

    delivery_days = np.clip(rng.normal(4.5, 2.0, size=n_orders), 1, 21).round().astype(
        int
    )

    is_weekend_order = rng.integers(0, 2, size=n_orders)

    customer_id = rng.integers(10000, 99999, size=n_orders)

    prev_return_ratio = np.divide(
        num_previous_returns,
        num_previous_orders,
        out=np.zeros(n_orders),
        where=num_previous_orders > 0,
    )
    price_by_cat_max = np.array([PRICE_RANGES[c][1] for c in categories])
    normalized_price = price_inr / price_by_cat_max
    is_return_prone_cat = np.isin(categories, list(RETURN_PRONE_CATEGORIES)).astype(
        float
    )
    is_cod = (payment_methods == "COD").astype(float)
    tenure_norm = customer_tenure_days / 2600.0

    z = (
        -2.1
        + 2.1 * prev_return_ratio
        + 0.5 * is_return_prone_cat
        + 0.012 * (discount_pct - 20)
        + 0.85 * is_cod
        + 0.09 * (delivery_days - 4.5)
        + 0.35 * normalized_price
        + 0.06 * is_weekend_order
        - 0.4 * np.tanh(tenure_norm * 3)
    )
    prob_return = 1.0 / (1.0 + np.exp(-z))
    returned = rng.binomial(1, prob_return)

    rating_given = rng.integers(1, 6, size=n_orders).astype(float)
    missing_prob = np.where(payment_methods == "COD", 0.21, 0.06)
    missing_mask = rng.uniform(size=n_orders) < missing_prob
    rating_given[missing_mask] = np.nan

    df = pd.DataFrame(
        {
            "order_id": np.arange(1, n_orders + 1),
            "customer_id": customer_id,
            "product_category": categories,
            "price_inr": price_inr,
            "discount_pct": discount_pct,
            "payment_method": payment_methods,
            "customer_tenure_days": customer_tenure_days,
            "num_previous_orders": num_previous_orders,
            "num_previous_returns": num_previous_returns,
            "delivery_distance_km": delivery_distance_km,
            "delivery_days": delivery_days,
            "is_weekend_order": is_weekend_order,
            "rating_given": rating_given,
            "returned": returned,
        }
    )
    return df


if __name__ == "__main__":
    out_dir = os.path.dirname(os.path.abspath(__file__))
    df = generate()
    out_path = os.path.join(out_dir, "orders.csv")
    df.to_csv(out_path, index=False)
    print("NOTE: this is SYNTHETIC data generated by this script, not real Flipkart data.")
    print(f"Wrote {len(df)} rows to {out_path}")
    print(f"Return rate: {df['returned'].mean():.4f}")
    print(f"rating_given missing rate: {df['rating_given'].isna().mean():.4f}")
    print(
        "Missing rate by payment method:\n",
        df.assign(missing=df["rating_given"].isna())
        .groupby("payment_method")["missing"]
        .mean(),
    )
